name: Go Tests

on:
  push:
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: go fmt
        run: make go.fmt

      - name: check diff
        run: |
          if ! git diff; then
            echo "Detected changes that have not been committed to the repository"
            exit 1
          fi

      - name: go vet
        run: make go.vet

      - name: go lint
        run: make go.lint

      - name: go staticcheck
        run: make go.staticcheck

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v2.4.0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Run tests
        run: make go.test
